
#****************************************************************************
#
# Makefile
# 
# This is a GNU make (gmake) makefile
# Author:Dive
#****************************************************************************
DIRS	:= src
TARGET	:= obj/${arm}/libplatform_customer.so

LIBS :=

INCDIRS	:=${DIRS} ./include
include ${SRC_TOPDIR}/comm_share.mk




	 